# Generated by Django 5.1.15 on 2026-10-06 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(default='Tailored Software Engineer', max_length=255)),
                ('target_company', models.CharField(blank=True, default='', max_length=255)),
                ('resume_content', models.JSONField(default=dict, help_text='Structured truthful tailored resume content.')),
                ('matched_skills', models.JSONField(default=list, help_text='Skills present in both JD and Master Profile.')),
                ('missing_skills', models.JSONField(default=list, help_text='Skills in JD that are missing from Master Profile (omitted from resume).')),
                ('ats_score', models.FloatField(default=0.0, help_text='Estimated ATS Compatibility Score (0-100).')),
                ('ats_breakdown', models.JSONField(default=dict, help_text='Detailed ATS scoring criteria, category breakdowns, and advice.')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes_pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
