# Generated by Django 5.1.15 on 2026-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_info',
            field=models.TextField(blank=True, default='', help_text='Additional factual details, awards, or custom notes.'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
